name: pgi-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1
  - scipy=1
  - matplotlib=3
  - scikit-learn=0
  - seaborn=0
  - mkl=2019
  - pip:
    - geoana==0.0.5
    - empymod==1.10.6
    - h5py==2.9.0
    - pymatsolver==0.1.2
    - discretize==0.3.8
    - git+https://github.com/simpeg/simpeg.git@examples/PGI
    - git+https://github.com/simpeg/simpegEM1D@examples/PGI
    - git+https://github.com/simpeg/tle-magnetotelluric_inversion@master
