name: pgi-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1
  - scipy=1
  - matplotlib=3
  - scikit-learn
  - seaborn=0
  - mkl=2019
  - pip:
    - geoana=0
    - empymod=1
    - h5py=2
    - pymatsolver=0
    - discretize=0
    - git+https://github.com/simpeg/simpeg.git@examples/PGI
    - git+https://github.com/simpeg/simpegEM1D@examples/PGI
    - git+https://github.com/simpeg/tle-magnetotelluric_inversion@master
