name: pgi-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15.4
  - scipy=1.1.0
  - matplotlib=3.0.2
  - scikit-learn=0.20.0
  - seaborn=0.9.0
  - mkl=2019.1
  - pip:
    - empymod==1.10.6
    - h5py==2.9.0
    - pymatsolver==0.1.2
    - discretize==0.3.8
    - git+https://github.com/simpeg/simpeg.git@examples/PGI
    - git+https://github.com/simpeg/simpegEM1D@examples/PGI
    - git+https://github.com/simpeg/tle-magnetotelluric_inversion@master
